# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/lo/Dropbox/2. Semester/Programmiersprachen/Übung/programmiersprachen-aufgabenblatt-2/source"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/lo/Dropbox/2. Semester/Programmiersprachen/Übung/programmiersprachen-aufgabenblatt-2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/lo/Dropbox/2. Semester/Programmiersprachen/Übung/programmiersprachen-aufgabenblatt-2/CMakeFiles" "/home/lo/Dropbox/2. Semester/Programmiersprachen/Übung/programmiersprachen-aufgabenblatt-2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/lo/Dropbox/2. Semester/Programmiersprachen/Übung/programmiersprachen-aufgabenblatt-2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/build
.PHONY : tests/fast

# target to build an object file
circle.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/circle.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/circle.o
.PHONY : circle.o

# target to preprocess a source file
circle.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/circle.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/circle.i
.PHONY : circle.i

# target to generate assembly for a file
circle.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/circle.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/circle.s
.PHONY : circle.s

# target to build an object file
example.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.o
.PHONY : example.o

# target to preprocess a source file
example.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.i
.PHONY : example.i

# target to generate assembly for a file
example.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.s
.PHONY : example.s

# target to build an object file
glew.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/glew.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/glew.o
.PHONY : glew.o

# target to preprocess a source file
glew.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/glew.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/glew.i
.PHONY : glew.i

# target to generate assembly for a file
glew.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/glew.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/glew.s
.PHONY : glew.s

# target to build an object file
mat2.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/mat2.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/mat2.o
.PHONY : mat2.o

# target to preprocess a source file
mat2.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/mat2.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/mat2.i
.PHONY : mat2.i

# target to generate assembly for a file
mat2.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/mat2.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/mat2.s
.PHONY : mat2.s

# target to build an object file
rectangle.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/rectangle.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/rectangle.o
.PHONY : rectangle.o

# target to preprocess a source file
rectangle.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/rectangle.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/rectangle.i
.PHONY : rectangle.i

# target to generate assembly for a file
rectangle.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/rectangle.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/rectangle.s
.PHONY : rectangle.s

# target to build an object file
tests.o:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.o
.PHONY : tests.o

# target to preprocess a source file
tests.i:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.i
.PHONY : tests.i

# target to generate assembly for a file
tests.s:
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/tests.s
.PHONY : tests.s

# target to build an object file
vec2.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/vec2.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/vec2.o
.PHONY : vec2.o

# target to preprocess a source file
vec2.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/vec2.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/vec2.i
.PHONY : vec2.i

# target to generate assembly for a file
vec2.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/vec2.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/vec2.s
.PHONY : vec2.s

# target to build an object file
window.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/window.o
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/window.o
.PHONY : window.o

# target to preprocess a source file
window.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/window.i
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/window.i
.PHONY : window.i

# target to generate assembly for a file
window.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/window.s
	$(MAKE) -f CMakeFiles/tests.dir/build.make CMakeFiles/tests.dir/window.s
.PHONY : window.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example"
	@echo "... tests"
	@echo "... circle.o"
	@echo "... circle.i"
	@echo "... circle.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... glew.o"
	@echo "... glew.i"
	@echo "... glew.s"
	@echo "... mat2.o"
	@echo "... mat2.i"
	@echo "... mat2.s"
	@echo "... rectangle.o"
	@echo "... rectangle.i"
	@echo "... rectangle.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
	@echo "... vec2.o"
	@echo "... vec2.i"
	@echo "... vec2.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

